<?php

class CT_CtSocial_Widget extends Case_Theme_Core_Widget_Base{
    protected $name = 'ct_social';
    protected $title = 'Case Social Icons';
    protected $icon = 'eicon-social-icons';
    protected $categories = array( 'case-theme-core' );
    protected $params = '{"sections":[{"name":"section_icon","label":"Icons","tab":"content","controls":[{"name":"layout","label":"Style","type":"select","options":{"1":"Layout 1","2":"Layout 2","3":"Layout 3"},"default":"1"},{"name":"icons","label":"Icons","type":"repeater","condition":{"layout":["1","2","3"]},"controls":[{"name":"ct_icon","label":"Icon","type":"icons","fa4compatibility":"icon","default":{"value":"fas fa-star","library":"fa-solid"},"recommended":{"fa-brands":["android","apple","behance","bitbucket","codepen","delicious","deviantart","digg","dribbble","elementor","facebook","flickr","foursquare","free-code-camp","github","gitlab","globe","houzz","instagram","jsfiddle","linkedin","medium","meetup","mix","mixcloud","odnoklassniki","pinterest","product-hunt","reddit","shopping-cart","skype","slideshare","snapchat","soundcloud","spotify","stack-overflow","steam","telegram","thumb-tack","tripadvisor","tumblr","twitch","twitter","viber","vimeo","vk","weibo","weixin","whatsapp","wordpress","xing","yelp","youtube","500px"],"fa-solid":["envelope","link","rss"]}},{"name":"icon_link","label":"Icon Link","type":"url"}]},{"name":"icon_space","label":"Icon Spacer","type":"slider","control_type":"responsive","size_units":["px"],"range":{"px":{"min":0,"max":300}},"selectors":{"{{WRAPPER}} .ct-social-icon1 a":"margin-right: {{SIZE}}{{UNIT}};","{{WRAPPER}} .ct-social-icon3 a + a":"margin-left: {{SIZE}}{{UNIT}};"},"condition":{"layout":["1","3"]}},{"name":"social_label","label":"Label","type":"text","condition":{"layout":["2"]}},{"name":"color_gr_from","label":"Color Gradient From","type":"color","condition":{"layout":["1","2"]}},{"name":"color_gr_to","label":"Color Gradient To","type":"color","condition":{"layout":["1","2"]}},{"name":"icon_color","label":"Icon Color","type":"color","selectors":{"{{WRAPPER}} .ct-social-icon3 a":"color: {{VALUE}};"},"condition":{"layout":["3"]}},{"name":"icon_color_hover","label":"Icon Color Hover","type":"color","selectors":{"{{WRAPPER}} .ct-social-icon3 a:hover":"color: {{VALUE}};"},"condition":{"layout":["3"]}}]}]}';
    protected $styles = array(  );
    protected $scripts = array( 'ct-inline-css-js' );
}